CREATE TABLE `sap-business-partner-customer-sales-area-data`
(
    `Customer`              varchar(10) DEFAULT NULL,
    `Customer_desc`         varchar(40) DEFAULT NULL,
    `SalesOrganization`     varchar(4) DEFAULT NULL,
    `DistributionChannel`   varchar(2) DEFAULT NULL,
    `Division`              varchar(2) DEFAULT NULL,
    `CompleteDeliveryIsDefined` tinyint(1) DEFAULT NULL,
    `Currency`              varchar(5) DEFAULT NULL,
    `CustomerAccountAssignmentGroup` varchar(2) DEFAULT NULL,
    `CustomerPaymentTerms`  varchar(4) DEFAULT NULL,
    `CustomerPriceGroup`    varchar(2) DEFAULT NULL,
    `CustomerPricingProcedure` varchar(2) DEFAULT NULL,
    `DeliveryPriority`      varchar(2) DEFAULT NULL,
    `IncotermsClassification` varchar(3) DEFAULT NULL,
    `InvoiceDate`           varchar(2) DEFAULT NULL,
    `OrderCombinationIsAllowed` tinyint(1) DEFAULT NULL,
    `PartialDeliveryIsAllowed` tinyint(1) DEFAULT NULL,
    `PriceListType`         varchar(2) DEFAULT NULL,
    `SalesGroup`            varchar(3) DEFAULT NULL,
    `SalesOffice`           varchar(4) DEFAULT NULL,
    `ShippingCondition`     varchar(2) DEFAULT NULL,
    `SupplyingPlant`        varchar(4) DEFAULT NULL,
    `SalesDistrict`         varchar(6) DEFAULT NULL,
    `InvoiceListSchedule`   varchar(2) DEFAULT NULL,
    `ExchangeRateType`      varchar(4) DEFAULT NULL,
    `OrderIsBlockedForCustomer` varchar(2) DEFAULT NULL,
    `DeliveryIsBlockedForCustomer` varchar(2) DEFAULT NULL,
    `BillingIsBlockedForCustomer` varchar(2) DEFAULT NULL,
    `DeletionIndicator`     tinyint(1) DEFAULT NULL,
    PRIMARY KEY (`Customer`, `SalesOrganization`, `DistributionChannel`, `Division`),
    CONSTRAINT `Customer_fk` FOREIGN KEY (`Customer`) REFERENCES `sap-business-partner-role-data` (`BusinessPartner`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
